name: cpp-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'

jobs:
  build:
    name: Create Release
    runs-on: macos-12
    env:
      targetZip: Hello-World-iOS-${{ github.ref_name }}.zip
    steps:
      - run: git clone https://github.com/cwalk/Hello-World-iOS
      
      - uses: mxcl/xcodebuild@v1.11.0
        with:
          working-directory: Hello-World-iOS
          platform: iOS
          action: build
          configuration: release
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "Hello-World-iOS"
          filename: "${{ env.targetZip }}"
       
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Hello-World-iOS/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
