name: cpp-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'

jobs:
  build:
    name: Create Release
    runs-on: macos-11
    env:
      targetIPA: Hello-World-iOS-${{ github.ref_name }}.zip
    steps:
      - uses: actions/checkout@v3
      
      - run: git clone https://github.com/cwalk/Hello-World-iOS
          
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.0.0'
          
      - name: Show Xcode version
        run: xcodebuild -version
          
# xcode-version: '13.4' # Exact version of a Xcode version to use
#           apple-id: 'bot@sinoru.io' # Apple ID to download from Apple Developer when Xcode not available in local
#           apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
          
#                     CODE_SIGN_IDENTITY="" \
      - run: |
          cd "Hello-World-iOS" && \
          workspace=$pwd && \
          xcodebuild -list -project "Hello World.xcodeproj" && \
          xcodebuild archive \
          -scheme "Hello World" \
          -destination 'generic/platform=iOS' \
          SWIFT_VERSION=5 \
          -sdk iphoneos \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGN_IDENTITY= \
          CODE_SIGN_ENTITLEMENTS= \
          GCC_OPTIMIZATION_LEVEL=s \
          SWIFT_OPTIMIZATION_LEVEL=-O \
          -archivePath hello_world.xcarchive && \
          cd ./hello_world.xcarchive/Products/Applications && \
          mkdir -p ./ipa/Payload && \
          cp -r "./Hello World.app"  ./ipa/Payload && \
          cd ipa && \
          zip -r "${{ env.targetIPA }}" *
          
          # && \
          # xcodebuild -exportArchive -archivePath hello_world.xcarchive -exportOptionsPlist ../ExportOptions.plist -exportPath hello_world.ipa
       
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Hello-World-iOS/hello_world.xcarchive/Products/Applications/ipa/${{ env.targetIPA }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
